[workspace]
members = [
    "agreement-client",
    "agreement-common",
    "agreement-models",
    "agreement-web",
]
resolver = "2"

[workspace.dependencies]
axum = { version = "0.8.0", features = ["macros"] }
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.134"
wasm-bindgen = "0.2.99"
