[workspace]
members = ["agreement-client", "agreement-models", "agreement-web"]
resolver = "2"

[workspace.dependencies]
serde = { version = "1.0.217", features = ["derive"] }
wasm-bindgen = "0.2.99"
