[package]
name = "agreement-client"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
agreement-models = { path = "../agreement-models" }
unladeapi = { path = "../unladeapi" }

getrandom = { version = "0.2", features = ["js"] }
wasm-bindgen.workspace = true
wasm-bindgen-futures = "0.4.49"
