[package]
name = "agreement-business"
version = "0.1.0"
edition = "2021"

[dependencies]
agreement-common = { path = "../agreement-common" }
agreement-models = { path = "../agreement-models" }

chrono.workspace = true
tokio.workspace = true
tracing.workspace = true
