[package]
name = "agreement-business"
version.workspace = true
edition.workspace = true

[dependencies]
agreement-common = { path = "../agreement-common" }
agreement-models = { path = "../agreement-models" }

chrono.workspace = true
tokio.workspace = true
tracing.workspace = true
