[package]
name = "agreement-models"
version.workspace = true
edition.workspace = true

[dependencies]
agreement-common = { path = "../agreement-common" }
unlader = { path = "../unlader" }

chrono.workspace = true
serde.workspace = true
wasm-bindgen.workspace = true
