[package]
name = "agreement-models"
version = "0.1.0"
edition = "2021"

[dependencies]
agreement-common = { path = "../agreement-common" }
unlader = { path = "../unlader" }

chrono.workspace = true
serde.workspace = true
wasm-bindgen.workspace = true
