[package]
name = "agreement-models"
version.workspace = true
edition.workspace = true

[dependencies]
agreement-common = { path = "../agreement-common" }
unlade = { path = "../unlade" }

chrono.workspace = true
serde.workspace = true
wasm-bindgen.workspace = true
