[package]
name = "agreement-validation0"
version.workspace = true
edition.workspace = true

[dependencies]
agreement-error = { path = "../agreement-error" }
agreement-models = { path = "../agreement-models" }
